### ISSUE TITLE
bot is currently not alive in the server and has not been for a long time

### ISSUE THREAD

**Issue by suburbGira** [nicl83/winbot#5]
please once again alive it i want to teach genai to do funny things to windows xp again

**Comment by suburbGira** [comment]
bot no work pls alive it :(

**Comment by SnenxyTengoku** [comment]
:trollface:

**Comment by suburbGira** [comment]
oh ew i forgot about this

**Comment by SnenxyTengoku** [comment]
just an fyi, this is currently being rewritten with support for qemu and so far its looking pretty good, check the qmp-rewrite branch if you wanna try it

**Comment by suburbGira** [comment]
didn't ask, stop reminding me this friendgroup existed
